# Powerlevel9k is the best theme for prompt, I like to keep it in dark gray colors
export DEFAULT_USER=awampler
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
P9K_LEFT_PROMPT_ELEMENTS=(host ssh user dir dir_writable vcs newline vi_mode pyenv )
P9K_RPROMPT_ON_NEWLINE=true
P9K_RIGHT_PROMPT_ELEMENTS=(status history time)
P9K_DIR_SHORTEN_LENGTH=35
P9K_DIR_BACKGROUND='238'
P9K_DIR_FOREGROUND='252'
P9K_STATUS_BACKGROUND='238'
P9K_STATUS_FOREGROUND='252'
P9K_CONTEXT_BACKGROUND='240'
P9K_CONTEXT_FOREGROUND='252'
P9K_TIME_BACKGROUND='238'
P9K_TIME_FOREGROUND='252'
P9K_HISTORY_BACKGROUND='240'
P9K_HISTORY_FOREGROUND='252'
#P9K_VI_MODE_INSERT_FOREGROUND='teal'
